$(document).ready(function(){
	$('#menu-button').click(function(){
		$('.mobile-view').addClass('menu-section-active')
	});

	$('#remove-menu').click(function(){
		$('.mobile-view').removeClass('menu-section-active')
	});
	$('#menu-overlay').click(function(){
		$('.mobile-view').removeClass('menu-section-active')
	});
	$('#menu-button').click(function(){
		$('.sidebar-menu').addClass('sidebar-menu-active')
	});

	$('#remove-menu').click(function(){
		$('.sidebar-menu').removeClass('sidebar-menu-active')
	});
	$('#menu-overlay').click(function(){
		$('.sidebar-menu').removeClass('sidebar-menu-active')
	});

	$('#client').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:false,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:2,
	        },
	        600:{
	            items:3,
	        },
	        1000:{
	            items:6,
	        }
	    }
	});

	$('#Upcoming-Events').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:false,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	        },
	        600:{
	            items:3,
	        },
	        1000:{
	            items:3,
	        }
	    }
	});
	$('#Poster').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:true,
	    dots:false,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:false,
	            dots:true,
	        },
	        600:{
	            items:3,
	        },
	        1000:{
	            items:3,
	        }
	    }
	});


	$('#Poster').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:true,
	    dots:false,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:false,
	            dots:true,
	        },
	        600:{
	            items:3,
	        },
	        1000:{
	            items:3,
	        }
	    }
	});


	$('#services-carousel').owlCarousel({
	    loop:true,
	    margin:10,
	    nav:true,
	    dots:false,
	    responsiveClass:true,
	    responsive:{
	        0:{
	            items:1,
	            nav:false,
	            dots:true,
	        },
	        600:{
	            items:3,
	        },
	        1000:{
	            items:3,
	        }
	    }
	});
});